language: en

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: custome_intent_classifier.CustomeIntentClassifier
  - name: DIETClassifier
    epochs: 1
  - name: EntitySynonymMapper

policies:
  - name: TwoStageFallbackPolicy
    core_threshold: 0.3
    nlu_threshold: 0.3
    fallback_core_action_name: "action_default_fallback"
    fallback_nlu_action_name: "action_default_fallback"
    deny_suggestion_intent_name: "out_of_scope"
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
